// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uedwtyfxgkyzxrkdlkzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZHd0eWZ4Z2t5enhya2Rsa3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzEwMzUsImV4cCI6MjA1OTk0NzAzNX0.iWFwbDryn2behr1hWf_B9fYeCs-G--33gsY6NZ_rdnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);